---
- hosts: nodes
  gather_facts: no
  become : yes
  tasks:
  - name: Include environment_vars.yml vars file
    include_vars: environment_vars.yml

  - name : Set environment variables
    lineinfile : 
      path : /etc/environment
      state : present
      regex : '{{item}}'
      line : '{{item}}'
    with_items: "{{ env }}"
