---
- hosts: jenkins
  gather_facts: no
  become : yes
  tasks:
  - name: Include mongodb_vars.yml vars file
    include_vars: mongodb_vars.yml

  - name : Import key from MongoDB
    apt_key :
      keyserver : hkp://keyserver.ubuntu.com:80
      id : 0C49F3730359A14518585931BC711F9BA15703C6
      state : present

  - name : Add MongoDB repository
    lineinfile :
      line : "deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse"
      dest : "/etc/apt/sources.list.d/mongodb-org-3.4.list"
      state : present
      create : yes

  - name : Install MongoDB
    apt :
      name : mongodb-org
      state : present
      update_cache : yes

  - name : Start mongodb server
    systemd : 
      name : mongod
      state : started
      enabled : yes

  - name: Install pymongo
    pip :
      name: pymongo
      state: present 

  - name: Adding mongo db user  
    mongodb_user:
      database: admin
      name: '{{user}}'
      password: '{{password}}'
      state: present