- hosts: nodes
  gather_facts: false
  become: true
  tasks:
    - name: Include job_vars.yml vars file
      include_vars: job_vars.yml

    - name: create jobs directory
      file:
        path: /jobs
        state: directory
      
    - name: Place build job file inside /jobs 
      copy:
        src: /ansible_srv/setup-playbooks/jobs/general_build_job.yml
        dest: /jobs/
      become: true    

    - name: Set job name in job file
      replace: dest=/jobs/general_build_job.yml regexp='job_name' replace='{{jobName}}' backup=yes
       
    - name: Set git url in job file
      replace: dest=/jobs/general_build_job.yml regexp='git_url' replace='{{gitUrl}}' backup=yes

    - name: Set buildPath in job file
      replace: dest=/jobs/general_build_job.yml regexp='build_path' replace='{{buildPath}}' backup=yes        

    - name: uninstall requests
      pip: 
        name: requests
        state: absent
        
    - name: install requests
      pip:
        name: requests 
        state: present    


    - name: create jenkins job
      command: jenkins-jobs update jobs
      args:
        chdir: /
      become: true   
