- hosts: nodes
  gather_facts: false
  become: true
  tasks:
    - name: install nodejs and npm
        apt: 
          name: ['nodejs','npm','nodejs-legacy']  
    
      - name: Updating node
        shell: |
                  npm cache clean -f
                  npm install -g n
                  n stable
        become: true 