- hosts: nodes
  gather_facts: false
  become: true
  tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        
    - name: Install pip
      apt:
        name: python3-pip
        update_cache: yes
        state: present
      become: true

    - name: update pip
      command: python3 -m pip install --upgrade pip

    - name: install nodejs and npm
      apt: 
        name: ['nodejs','npm']   
    
    - name: Install jenkins-job-builder using pip
      pip:
        name: jenkins-job-builder 
    
    - name: ansible create directory /etc/jenkins_jobs/
      file:
        path: /etc/jenkins_jobs/
        state: directory

    - name: init password jenkin
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: admin_password

    - name: Place jenkins_job.ini to etc/jenkins_jobs directory
      copy:
        src: /ansible_srv/jenkins_jobs.ini
        dest: /etc/jenkins_jobs/
      become: true

    - name: place the password in the jenkins_jobs.ini file
      lineinfile:
        path: /etc/jenkins_jobs/jenkins_jobs.ini
        line: password={{ admin_password.stdout }}  
    
    - name: create jobs directory
      file:
        path: /jobs
        state: directory
      
    - name: Place checkbox-build job file inside /jobs 
      copy:
        src: /ansible_srv/jobs/checkbox-build.yml
        dest: /jobs/
      become: true    

    - name: Clone checkboxio git repo into /home/vagrant/
      git:
        repo: 'https://github.com/ppvasude/checkbox.io.git'
        dest: /home/vagrant/checkboxio/
        clone: yes
        update: yes  
      become: true

    - name: uninstall requests
      pip: 
        name: requests
        state: absent
        
    - name: install requests
      pip:
        name: requests 
        state: present    


    - name: create jenkins job
      command: jenkins-jobs update jobs
      args:
        chdir: /
      become: true   

