- hosts: localhost
  vars:
    ec2_access_key: <Your AWS Access Key>
    ec2_secret_key: <Your AWS Secret key>
    key_name: <Your private key name>

  tasks:

    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes

    - name: Install pip
      apt: 
        name: ['python-pip']
        state: present
      become: true

    - name: Install boto
      pip:
        name: boto

    - name: Provision a set of instances
      ec2:
        aws_access_key: "{{ec2_access_key}}"
        aws_secret_key: "{{ec2_secret_key}}"
        key_name: "{{key_name}}"
        region: us-east-2
        instance_type: t2.micro
        image: ami-0cd3dfa4e37921605
        wait: yes
        count: 1
        vpc_subnet_id: subnet-836b07f9
        assign_public_ip: yes
      register: ec2

    - name: Print public IP of created ec2 instance
      debug:
        var: ec2.instances[0].public_ip

    - name: Add host to [nodes] in inventory file
      lineinfile:
        path: /ansible_srv/inventory
        line: '{{ec2.instances[0].public_ip}} ansible_ssh_user=ec2-user ansible_ssh_private_key_file=~/.ssh/DevOps-Project-Key'
  
    