- job:
    name: checkboxio_build
    auth-token: testToken
    scm:
      - git:
          url: https://github.com/Madhu-Vamsi/checkbox.io.git
    builders:
      - shell: |
                  cd /var/lib/jenkins/workspace/checkboxio_build/server-side/site
                  npm install
                  npm test  
    triggers:
      - pollscm:
          cron: 'H/15 * * * *'
