- job:
    name: job_name
    auth-token: testToken
    scm:
      - git:
          url: git_url
    builders:
      - shell: |
                  cd /var/lib/jenkins/workspace/job_name/build_path
                  npm install
                  npm test  
    triggers:
      - pollscm:
          cron: 'H/15 * * * *'
