---
- hosts: all
  gather_facts: no
  become : yes
  vars :
    mysql_password : <mysql password>
  tasks:
  - name : Update and Upgrade
    apt :
      update_cache : yes
      cache_valid_time : 86400
      upgrade : yes
  - name : Install Maven
    apt :
      name : maven
      state : present
  - name : Install openjdk
    apt :
      name : openjdk-8-jdk
      state : present
  - name : MySQL set root password
    debconf :
      name : mysql-server
      question : mysql-server/root_password
      value : '{{mysql_password}}'
      vtype : password
  - name : Set password again
    debconf :
      name : mysql-server
      question : mysql-server/root_password_again
      value : '{{ mysql_password }}'
      vtype : password
  - name : Install Mysql
    apt :
      name : mysql-server
      state : present
  - name : Install Git
    apt :
      name : git
      state : present
  - name: Place iTrust-build job file inside /jobs 
    copy:
      src: /ansible_srv/jobs/iTrust-build.yml
      dest: /jobs/
  - name : Set up sudo credentials
    lineinfile : 
      path : /etc/sudoers
      state : present
      regex : 'jenkins ALL=(ALL) NOPASSWD: ALL'
      line : 'jenkins ALL=(ALL) NOPASSWD: ALL'
  - name : copy playbooks to jenkins server
    copy:
      src : /ansible_srv/file-templates
      dest : /
  - name : Install software-properties-common that allows us to work easily with ppa
    apt :
      name : software-properties-common
      update_cache : yes
  - name : Configure ansible ppa to the system
    apt_repository: 
      repo: 'ppa:ansible/ansible' 
      state: present 
      update_cache: yes
  - name : Install Ansible
    apt :
      name : ansible
      state : present
  - name: create jenkins job
    command: jenkins-jobs update jobs
    args:
      chdir: /
    become: true       