---
- name: install wget
  yum:
    name: wget
    state: present

- name: install openjdk
  yum:
    name: java-1.8.0-openjdk
    state: present
  become: true

- name: remove java-1.7.0-openjdk
  yum:
    name: java-1.7.0-openjdk
    state: removed
  become: true  

- name: download jenkins.repo
  get_url:
    url: http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo

- name: import jenkins key
  rpm_key:
    state: present
    key: https://jenkins-ci.org/redhat/jenkins-ci.org.key

- name: install jenkins
  yum:
    name: jenkins
    state: present

- name: start jenkins
  service: state=started name=jenkins enabled=yes
  become: true

- name: sleep for 30 seconds and continue with play
  wait_for: timeout=30
  delegate_to: localhost  

- name: init password jenkin
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result

- name: print init password jenkins
  debug:
    var: result.stdout